[Config]
toggle=false
device="/dev/input/event0"

[Keymap]
"RIGHTALT"="CAPSLOCK"

[Keymap.CAPSLOCK]
"I"="UP"
"K"="DOWN"
"J"="LEFT"
"L"="RIGHT"
"B"="BACKSPACE"
"F"="ESC"
"N"="LEFTSHIFT+MINUS"
"APOSTROPHE"="GRAVE"
